// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5U4p7ABL6Yz_5FYAx_CjUO0rfW_EBXLE',
    appId: '1:834260398745:web:68633d9b200a0df4563e08',
    messagingSenderId: '834260398745',
    projectId: 'my-cooking-helper-656ab',
    authDomain: 'my-cooking-helper-656ab.firebaseapp.com',
    storageBucket: 'my-cooking-helper-656ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvulDuJSpkZxFIQafN4Zzjou1VrpUaE8U',
    appId: '1:834260398745:android:17dec216c0b23f5b563e08',
    messagingSenderId: '834260398745',
    projectId: 'my-cooking-helper-656ab',
    storageBucket: 'my-cooking-helper-656ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnQbCPqZ5bjgNWaFate7U7O3T9O1fYzAY',
    appId: '1:834260398745:ios:977c12458c200fe5563e08',
    messagingSenderId: '834260398745',
    projectId: 'my-cooking-helper-656ab',
    storageBucket: 'my-cooking-helper-656ab.firebasestorage.app',
    iosBundleId: 'com.example.myCookingHelper',
  );
}
