class PreferencesOptions {
  static const genders = [
    {"label": "Male", "emoji": "👨‍🍳"},
    {"label": "Female", "emoji": "👩‍🍳"},
    {"label": "Non-binary", "emoji": "🧑‍🍳"},
    {"label": "Prefer not to say", "emoji": "🤫"},
    {"label": "Other", "emoji": "❓"},
  ];

  static const cookingTimes = [
    {"label": "Quick (< 20 min)", "emoji": "⚡"},
    {"label": "Moderate (20–45 min)", "emoji": "⏰"},
    {"label": "Extended (> 45 min)", "emoji": "🕰️"},
    {"label": "Batch Cooking", "emoji": "📦"},
    {"label": "Meal Prep for the Week", "emoji": "📅"},
    {"label": "Varies day to day", "emoji": "🔄"},
  ];

  static const allergies = [
    {"label": "Dairy", "emoji": "🥛"},
    {"label": "Gluten", "emoji": "🌾"},
    {"label": "Nuts (all)", "emoji": "🥜"},
    {"label": "Peanuts", "emoji": "🥜"},
    {"label": "Tree Nuts", "emoji": "🌰"},
    {"label": "Soy", "emoji": "🌱"},
    {"label": "Shellfish", "emoji": "🦐"},
    {"label": "Crustaceans", "emoji": "🦀"},
    {"label": "Molluscs", "emoji": "🦪"},
    {"label": "Eggs", "emoji": "🥚"},
    {"label": "Fish", "emoji": "🐟"},
    {"label": "Sesame", "emoji": "🌻"},
    {"label": "Corn", "emoji": "🌽"},
    {"label": "Mustard", "emoji": "🌿"},
    {"label": "Celery", "emoji": "🥬"},
    {"label": "Sulphites", "emoji": "💨"},
    {"label": "MSG", "emoji": "🍜"},
    {"label": "Lactose intolerance", "emoji": "🚫🥛"},
    {"label": "None", "emoji": "👍"},
    {"label": "Other", "emoji": "❓"},
  ];

  static const diets = [
    {"label": "Vegan", "emoji": "🌱"},
    {"label": "Vegetarian (Lacto)", "emoji": "🥛"},
    {"label": "Vegetarian (Ovo)", "emoji": "🥚"},
    {"label": "Pescatarian", "emoji": "🐟"},
    {"label": "Flexitarian", "emoji": "🍽️"},
    {"label": "Paleo", "emoji": "🥩"},
    {"label": "Keto", "emoji": "🥓"},
    {"label": "Low-carb", "emoji": "🥗"},
    {"label": "High Protein", "emoji": "🍗"},
    {"label": "Carnivore", "emoji": "🍖"},
    {"label": "Raw Food", "emoji": "🥒"},
    {"label": "Whole30", "emoji": "🧘"},
    {"label": "Intermittent Fasting", "emoji": "⏳"},
    {"label": "Kosher", "emoji": "✡️"},
    {"label": "Halal", "emoji": "☪️"},
    {"label": "Gluten-free", "emoji": "🚫🌾"},
    {"label": "Low FODMAP", "emoji": "🦠"},
    {"label": "Diabetic-friendly", "emoji": "🍏"},
    {"label": "Mediterranean", "emoji": "🍅"},
    {"label": "DASH", "emoji": "💪"},
    {"label": "None / Open to all", "emoji": "👌"},
    {"label": "Other", "emoji": "❓"},
  ];

  static const cuisines = [
    {"label": "Italian", "emoji": "🍝"},
    {"label": "Chinese", "emoji": "🥡"},
    {"label": "Mexican", "emoji": "🌮"},
    {"label": "Indian", "emoji": "🍛"},
    {"label": "Japanese", "emoji": "🍣"},
    {"label": "Thai", "emoji": "🍜"},
    {"label": "Korean", "emoji": "🍲"},
    {"label": "Vietnamese", "emoji": "🥢"},
    {"label": "Spanish", "emoji": "🥘"},
    {"label": "Mauritian/Creole", "emoji": "🍲"},
    {"label": "Caribbean", "emoji": "🏝️"},
    {"label": "Brazilian", "emoji": "🥥"},
    {"label": "French", "emoji": "🥖"},
    {"label": "Middle Eastern", "emoji": "🥙"},
    {"label": "African", "emoji": "🍲"},
    {"label": "Scandinavian", "emoji": "🥔"},
    {"label": "Russian", "emoji": "🍲"},
    {"label": "Mediterranean", "emoji": "🥗"},
    {"label": "American", "emoji": "🍔"},
    {"label": "British", "emoji": "🥧"},
    {"label": "Other", "emoji": "❓"},
  ];

  static const spiceLevels = [
    {"label": "No Spice", "emoji": "😐"},
    {"label": "Mild", "emoji": "🌶️"},
    {"label": "Medium", "emoji": "🌶️🌶️"},
    {"label": "Spicy", "emoji": "🌶️🌶️🌶️"},
    {"label": "Super Spicy!", "emoji": "🔥"},
    {"label": "Surprise me!", "emoji": "🎲"},
    {"label": "No preference", "emoji": "❔"},
  ];

  static const barriers = [
    {"label": "Cooking takes too much time", "emoji": "⏳"},
    {"label": "Don’t know what to cook", "emoji": "🤔"},
    {"label": "Lack of ingredients", "emoji": "🛒"},
    {"label": "Work/Busy schedule", "emoji": "💼"},
    {"label": "Lack of confidence/skills", "emoji": "🙈"},
    {"label": "Cleaning up is difficult", "emoji": "🧹"},
    {"label": "Cooking for one is not fun", "emoji": "👤"},
    {"label": "Kids are picky", "emoji": "🧒"},
    {"label": "Limited kitchen tools", "emoji": "🔪"},
    {"label": "Too expensive", "emoji": "💸"},
    {"label": "Health issues", "emoji": "💊"},
    {"label": "Eating out is easier", "emoji": "🍽️"},
    {"label": "Other", "emoji": "❓"},
  ];
}
